In [32]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [39]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [40]:
train

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [41]:
test

     PassengerId  Pclass                                          Name  ...      Fare  Cabin  Embarked
0            892       3                              Kelly, Mr. James  ...    7.8292    NaN         Q
1            893       3              Wilkes, Mrs. James (Ellen Needs)  ...    7.0000    NaN         S
2            894       2                     Myles, Mr. Thomas Francis  ...    9.6875    NaN         Q
3            895       3                              Wirz, Mr. Albert  ...    8.6625    NaN         S
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  ...   12.2875    NaN         S
..           ...     ...                                           ...  ...       ...    ...       ...
413         1305       3                            Spector, Mr. Woolf  ...    8.0500    NaN         S
414         1306       1                  Oliva y Ocana, Dona. Fermina  ...  108.9000   C105         C
415         1307       3                  Saether, Mr. Simon Sivertsen  ...    7.2500    NaN         S
416         1308       3                           Ware, Mr. Frederick  ...    8.0500    NaN         S
417         1309       3                      Peter, Master. Michael J  ...   22.3583    NaN         C

[418 rows x 11 columns]

In [42]:
train["Age"].fillna(train["Age"].median(),inplace=True)
test["Age"].fillna(test["Age"].median(),inplace=True)

train["Fare"].fillna(train["Fare"].median(),inplace=True)
test["Fare"].fillna(test["Fare"].median(),inplace=True)

train["Embarked"].fillna(train["Embarked"].mode()[0],inplace=True)
test["Embarked"].fillna(test["Embarked"].mode()[0],inplace=True)

train["Sex"]=train["Sex"].map({"male":0, "female":1})
test["Sex"]=test["Sex"].map({"male":0, "female":1})

train=pd.get_dummies(train,columns=["Embarked"])
test=pd.get_dummies(test,columns=["Embarked"])

features=["Pclass","Sex","Age","SibSp","Parch","Fare"]

X=train[features]
y=train["Survived"]

rf=RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(X,y)

pred=rf.predict(test[features])

sub=pd.DataFrame({
    "PassengerId":test["PassengerId"],
    "Survived":pred
})

sub.to_csv("Submission.csv",index=False)

C:\Users\sumit\AppData\Local\Temp\ipykernel_19396\788842036.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train["Age"].fillna(train["Age"].median(),inplace=True)
C:\Users\sumit\AppData\Local\Temp\ipykernel_19396\788842036.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test["Age"].fillna(test["Age"].median(),inplace=True)
C:\Users\sumit\AppData\Local\Temp\ipykernel_19396\788842036.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train["Fare"].fillna(train["Fare"].median(),inplace=True)
C:\Users\sumit\AppData\Local\Temp\ipykernel_19396\788842036.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test["Fare"].fillna(test["Fare"].median(),inplace=True)
C:\Users\sumit\AppData\Local\Temp\ipykernel_19396\788842036.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train["Embarked"].fillna(train["Embarked"].mode()[0],inplace=True)
C:\Users\sumit\AppData\Local\Temp\ipykernel_19396\788842036.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test["Embarked"].fillna(test["Embarked"].mode()[0],inplace=True)

In [29]:
print(train.columns.tolist())

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked_C', 'Embarked_Q', 'Embarked_S']

In [43]:
import pandas as pd

df = pd.read_csv("Submission.csv")
print(df.columns)
print(df.head())

Index(['PassengerId', 'Survived'], dtype='object')
   PassengerId  Survived
0          892         0
1          893         0
2          894         1
3          895         1
4          896         0

In [44]:
import os

for file in os.listdir():
    if "Submission" in file or "submission" in file:
        print(file)

gender_submission.csv
Submission.csv

In [45]:
import os
print(os.path.abspath("submission.csv"))

C:\Users\sumit\submission.csv